### ISSUE TITLE
Fabric Browser - Account Names not retained and displayed in Accounts Tab

### ISSUE THREAD

**Issue by elv-arun** [eluv-io/elv-client-js#85]
When a new user is created and an account name is added in the profile, the account name is not being displayed in the Account tabs.

Reproduces on https://core.test.contentfabric.io/testv2/#/accounts

<img width="434" alt="Screen Shot 2020-08-11 at 1 36 27 PM" src="https://user-images.githubusercontent.com/63886822/89946664-1f229380-dbd8-11ea-9810-fa3312f82d2f.png">

**Comment by elv-kevin** [comment]
Addressed this in elv-core-js@4cfcbe68818000b724ff2c044115729d6a421ff5

The reason account names weren't showing up is because in authv3, user profiles are no longer public, so core could no longer user metadata unless that user was logged in.

I updated core to save the name and profile image for each account in localstorage. Those will be saved as you log into the accounts (i.e. it won't fix the issue immediately)

I also added the account selection dropdown to the login prompt (that pops up e.g. when you open a fabric browser link) so you can switch accounts more easily.
